'''
Created on Dec 15, 2018

@author: willh
'''

world_sizes = ("Tiny", "Small", "Standard", "Large")

world_types = ("Asteroid Belt",
               "Ice",
               "Sulfur",
               "Rock",
               "Hadean",
               "Ammonia",
               "Ocean",
               "Garden",
               "Greenhouse",
               "Cthonian")

world_climates = ("Frozen",
                  "Very Cold",
                  "Cold",
                  "Chilly",
                  "Cool",
                  "Normal",
                  "Warm",
                  "Tropical",
                  "Hot",
                  "Very Hot",
                  "Infernal")

chemical_basis = ("Hydrogen-Based",
                  "Hydrogen-Based",
                  "Hydrogen-Based",
                  "Ammonia-Based",
                  "Ammonia-Based",
                  "Hydrocarbon-Based",
                  "Water-Based",
                  "Water-Based",
                  "Water-Based",
                  "Chlorine-Based",
                  "Silicon/Sulfuric Acid",
                  "Silicon/Liquid Sulfur",
                  "Silicon/Liquid Rock",
                  "Plasma",
                  "Exotica",
                  "Exotica")

# not used in any code, defined as a reference
hab_type = ("Space-Dwelling",
            "Gas Giant",
            "Planetary Interior",
            "Water",
            "Land")

hab_land = ("Plains",
            "Plains",
            "Plains",
            "Plains",
            "Plains",
            "Desert",
            "Island/Beach",
            "Woodlands",
            "Swampland",
            "Mountain",
            "Arctic",
            "Jungle",
            "Jungle",
            "Jungle",
            "Jungle",
            "Jungle")

hab_water = ("Banks",
             "Banks",
             "Banks",
             "Banks",
             "Banks",
             "Open Ocean",
             "Fresh-Water Lakes",
             "River/Stream",
             "Tropical Lagoon",
             "Deep-Ocean Vents",
             "Salt-Water Sea",
             "Reef",
             "Reef",
             "Reef",
             "Reef",
             "Reef")

troph_ordinary = ("Combined",
                  "Autotroph",
                  "Decomposer",
                  "Scavenger",
                  "Omnivore",
                  "Gathering Herbivore",
                  "Gathering Herbivore",
                  "Grazing/Browsing Herbivore",
                  "Grazing/Browsing Herbivore",
                  "Pouncing Carnivore",
                  "Chasing Carnivore",
                  "Trapping Carnivore",
                  "Hijacking Carnivore",
                  "Filter-Feeder",
                  "Parasite/Symbiont",
                  "Parasite/Symbiont")

troph_sapient = ("Combined",
                 "Parasite/Symbiont",
                 "Filter-Feeder",
                 "Pouncing Carnivore",
                 "Scavenger",
                 "Gathering Herbivore",
                 "Gathering Herbivore",
                 "Omnivore",
                 "Chasing Carnivore",
                 "Chasing Carnivore",
                 "Grazing/Browsing Herbivore",
                 "Hijacking Carnivore",
                 "Trapping Carnivore",
                 "Trapping Carnivore",
                 "Decomposer",
                 "Autotroph")

troph_auto = ("Photosynthetic Autotroph",
              "Photosynthetic Autotroph",
              "Photosynthetic Autotroph",
              "Chemosynthetic Autotroph",
              "Chemosynthetic Autotroph",
              "Exotic Autotroph")

loco_primary = {
        "Arctic": ("Immobile",
                   "Slithering",
                   "Slithering",
                   "Swimming",
                   "Swimming",
                   "Digging",
                   "Walking",
                   "Walking",
                   "Winged Flight",
                   "Winged Flight",
                   "Special",
                   "Special"),

        "Banks": ("Immobile",
                  "Immobile",
                  "Floating",
                  "Sailing",
                  "Swimming",
                  "Swimming",
                  "Swimming",
                  "Winged Flight",
                  "Winged Flight",
                  "Winged Flight",
                  "Special",
                  "Special"),

        "Open Ocean": ("Immobile",
                       "Immobile",
                       "Floating",
                       "Sailing",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Winged Flight",
                       "Winged Flight",
                       "Winged Flight",
                       "Special",
                       "Special"),

        "Deep-Ocean Vents": ("Immobile",
                             "Immobile",
                             "Immobile",
                             "Immobile",
                             "Floating",
                             "Digging",
                             "Walking",
                             "Walking",
                             "Swimming",
                             "Swimming",
                             "Swimming",
                             "Swimming"),

        "Reef": ("Immobile",
                 "Immobile",
                 "Immobile",
                 "Immobile",
                 "Floating",
                 "Digging",
                 "Walking",
                 "Walking",
                 "Swimming",
                 "Swimming",
                 "Swimming",
                 "Swimming"),

        "Desert": ("Immobile",
                   "Slithering",
                   "Slithering",
                   "Digging",
                   "Walking",
                   "Walking",
                   "Walking",
                   "Winged Flight",
                   "Winged Flight",
                   "Winged Flight",
                   "Special",
                   "Special"),

        "Gas Giant": ("Swimming",
                      "Swimming",
                      "Swimming",
                      "Swimming",
                      "Winged Flight",
                      "Winged Flight",
                      "Winged Flight",
                      "Bouyant Flight",
                      "Bouyant Flight",
                      "Bouyant Flight",
                      "Bouyant Flight",
                      "Bouyant Flight"),

        "Island/Beach": ("Immobile",
                         "Slithering",
                         "Slithering",
                         "Digging",
                         "Walking",
                         "Walking",
                         "Climbing",
                         "Swimming",
                         "Winged Flight",
                         "Winged Flight",
                         "Special",
                         "Special"),

        "Tropical Lagoon": ("Immobile",
                            "Immobile",
                            "Immobile",
                            "Floating",
                            "Slithering",
                            "Walking",
                            "Digging",
                            "Swimming",
                            "Winged Flight",
                            "Winged Flight",
                            "Special",
                            "Special"),

        "Fresh-Water Lakes": ("Immobile",
                              "Immobile",
                              "Floating",
                              "Walking",
                              "Slithering",
                              "Swimming",
                              "Swimming",
                              "Swimming",
                              "Winged Flight",
                              "Winged Flight",
                              "Special",
                              "Special"),

        "Salt-Water Sea": ("Immobile",
                           "Immobile",
                           "Floating",
                           "Walking",
                           "Slithering",
                           "Swimming",
                           "Swimming",
                           "Swimming",
                           "Winged Flight",
                           "Winged Flight",
                           "Special",
                           "Special"),

        "Mountain": ("Immobile",
                     "Slithering",
                     "Slithering",
                     "Digging",
                     "Walking",
                     "Walking",
                     "Climbing",
                     "Winged Flight",
                     "Winged Flight",
                     "Winged Flight",
                     "Special",
                     "Special"),

        "Plains": ("Immobile",
                   "Slithering",
                   "Slithering",
                   "Digging",
                   "Walking",
                   "Walking",
                   "Walking",
                   "Winged Flight",
                   "Winged Flight",
                   "Winged Flight",
                   "Special",
                   "Special"),

        "Planetary Interior": ("Immobile",
                               "Immobile",
                               "Immobile",
                               "Immobile",
                               "Immobile",
                               "Digging",
                               "Digging",
                               "Digging",
                               "Digging",
                               "Digging",
                               "Digging",
                               "Digging"),

        "River/Stream": ("Immobile",
                         "Immobile",
                         "Floating",
                         "Slithering",
                         "Digging",
                         "Walking",
                         "Swimming",
                         "Swimming",
                         "Winged Flight",
                         "Winged Flight",
                         "Special",
                         "Special"),

        "Space-Dwelling": ("Immobile",
                           "Immobile",
                           "Immobile",
                           "Immobile",
                           "Immobile",
                           "Solar Sail",
                           "Solar Sail",
                           "Solar Sail",
                           "Solar Sail",
                           "Solar Sail",
                           "Rocket",
                           "Rocket"),

        "Swampland": ("Immobile",
                      "Swimming",
                      "Swimming",
                      "Swimming",
                      "Slithering",
                      "Digging",
                      "Walking",
                      "Climbing",
                      "Winged Flight",
                      "Winged Flight",
                      "Special",
                      "Special"),

        "Woodlands": ("Immobile",
                      "Slithering",
                      "Slithering",
                      "Digging",
                      "Walking",
                      "Walking",
                      "Climbing",
                      "Climbing",
                      "Winged Flight",
                      "Winged Flight",
                      "Special",
                      "Special"),

        "Jungle": ("Immobile",
                   "Slithering",
                   "Slithering",
                   "Digging",
                   "Walking",
                   "Walking",
                   "Climbing",
                   "Climbing",
                   "Winged Flight",
                   "Winged Flight",
                   "Special",
                   "Special")

        }

loco_second_water = {
        "Climbing": ("Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Walking",
                     "Walking",
                     "Walking",
                     "Walking",
                     "Walking",
                     ""),

        "Digging": ("Slithering",
                    "Slithering",
                    "Slithering",
                    "Slithering",
                    "Walking",
                    "Walking",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    ""),

        "Slithering": ("Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "Swimming",
                       "",
                       ""),

        "Swimming": ("Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Walking",
                     "Walking",
                     "Walking",
                     "",
                     "",
                     ""),

        "Walking": ("Swimming",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    "Swimming",
                    "",
                    "",
                    "",
                    ""),

        "Winged Flight": ("Climbing",
                          "Climbing",
                          "Climbing",
                          "Climbing",
                          "Swimming",
                          "Swimming",
                          "Walking",
                          "Walking",
                          "Walking",
                          "Slithering",
                          "")

        }

loco_second_land = {
        "Climbing": ("Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Walking",
                     "Walking",
                     "Walking",
                     "Walking",
                     "Walking",
                     ""),

        "Digging": ("Slithering",
                    "Slithering",
                    "Slithering",
                    "Slithering",
                    "Slithering",
                    "Walking",
                    "Walking",
                    "Walking",
                    "Walking",
                    "Walking",
                    ""),

        "Swimming": ("Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Slithering",
                     "Walking",
                     "Walking",
                     "Walking",
                     "",
                     "",
                     ""),

        "Walking": ("Slithering",
                    "Slithering",
                    "Digging",
                    "Walking",
                    "Walking",
                    "Climbing",
                    "Winged Flight",
                    "Winged Flight",
                    "Winged Flight",
                    "Special",
                    "Special"),

        "Winged Flight": ("Climbing",
                          "Climbing",
                          "Climbing",
                          "Climbing",
                          "Swimming",
                          "Swimming",
                          "Walking",
                          "Walking",
                          "Walking",
                          "Slithering",
                          "")

        }

loco_primary_extra = {

        "Arctic": ("Swimming", "Digging"),
        "Banks": ("Winged Flight"),
        "Open Ocean": ("Winged Flight"),
        "Deep-Ocean Vents": ("Digging", "Walking"),
        "Reef": ("Digging", "Walking"),
        "Desert": ("Digging", "Winged Flight"),
        "Gas Giant": (),
        "Island/Beach": ("Digging", "Climbing", "Swimming", "Winged Flight"),
        "Tropical Lagoon": ("Slithering", "Walking", "Digging"),
        "Fresh-Water Lakes": ("Walking", "Slithering"),
        "Salt-Water Sea": ("Walking", "Slithering"),
        "Mountain": ("Digging", "Walking", "Climbing", "Winged Flight"),
        "Plains": ("Digging", "Winged Flight"),
        "Planetary Interior": (),
        "River/Stream": ("Slithering", "Digging", "Walking"),
        "Space-Dwelling": (),
        "Swampland": ("Swimming", "Digging", "Climbing"),
        "Woodlands": ("Digging", "Climbing", "Winged Flight"),
        "Jungle": ("Digging", "Climbing", "Winged Flight")

        }

loco_second_extra = {

        "Climbing": (),
        "Digging": ("Slithering", "Walking"),
        "Slithering": (),
        "Swimming": (),
        "Walking": (),
        "Winged Flight": ("Climbing", "Swimming", "Slithering")

        }

size_class = ("Small", "Human-Scale", "Large", "Huge")

size_volume_small = (0.05, 0.07, 0.1, 0.15, 0.2, 0.3)
size_volume_human = (0.5, 0.7, 1, 1.5, 2, 3)
size_volume_large = (5, 7, 10, 15, 20, 99999)

# tables of (gravity, volume multiplier) pairs to use in chain where
# if gravity < value, multiplier = value
size_volume_gravity = ((0.15, 4.6), (0.25, 2.9), (0.35, 2.2), (0.45, 1.8),
                       (0.55, 1.6), (0.65, 1.4), (0.75, 1.3), (0.85, 1.2),
                       (0.95, 1.1), (1.125, 1), (1.375, 0.9), (1.75, 0.75),
                       (2.25, 0.6), (3, 0.5), (4.25, 0.4))

size_mass_small = (0.003, 0.01, 0.025, 0.08, 0.2, 1)
size_mass_human = (4, 9, 25, 80, 200, 600)
size_mass_large = (3000, 8000, 24000, 80000, 200000, 99999)

symmetry = ("Bilateral",
            "Bilateral",
            "Bilateral",
            "Bilateral",
            "Bilateral",
            "Bilateral",
            "Trilateral",
            "Radial",
            "Spherical",
            "Asymmetric",
            "Asymmetric",
            "Asymmetric",
            "Asymmetric")

tail_features = ("",
                 "",
                 "",
                 "",
                 "Striker",
                 "Long",
                 "Constricting",
                 "Barbed Striker",
                 "Gripping",
                 "Branching",
                 "Combination")

skeleton = ("None",
            "None",
            "Hydrostatic",
            "Hydrostatic",
            "External",
            "External",
            "Internal",
            "Internal",
            "Internal",
            "Combination",
            "Combination",
            "Combination",
            "Combination",
            "Combination",
            "Combination")

skin_covertype = ("Skin",
                  "Skin",
                  "Scales",
                  "Fur",
                  "Feathers",
                  "Exoskeleton")

skin_skin = ("Soft Skin",
             "Soft Skin",
             "Soft Skin",
             "Normal Skin",
             "Hide (DR 1)",
             "Hide (DR 1)",
             "Thick Hide (DR 4)",
             "Armor Shell (DR 5)",
             "Blubber",
             "Blubber",
             "Blubber",
             "Blubber",
             "Blubber",
             "Blubber")

skin_scales = ("Normal Skin",
               "Normal Skin",
               "Scales (DR 1)",
               "Scales (DR 1)",
               "Scales (DR 1)",
               "Scales (DR 1)",
               "Scales (DR 1)",
               "Heavy Scales (DR 3)",
               "Heavy Scales (DR 3)",
               "Armor Shell (DR 5)",
               "Armor Shell (DR 5)",
               "Armor Shell (DR 5)",
               "Armor Shell (DR 5)")

skin_fur = ("Normal Skin",
            "Normal Skin",
            "Normal Skin",
            "Normal Skin",
            "Fur",
            "Fur",
            "Thick Fur (+1 Temperature Tolerance)",
            "Thick Fur (+1 Temperature Tolerance)",
            "Thick Fur over Hide (DR 1, +1 Temperature Tolerance)",
            "Thick Fur over Hide (DR 1, +1 Temperature Tolerance)",
            "Spines",
            "Spines",
            "Spines")

skin_feathers = ("Normal Skin",
                 "Normal Skin",
                 "Normal Skin",
                 "Normal Skin",
                 "Feathers (+1 Temperature Tolerance)",
                 "Feathers (+1 Temperature Tolerance)",
                 "Feathers (+1 Temperature Tolerance)",
                 "Thick Feathers (+2 Temperature Tolerance)",
                 "Thick Feathers (+2 Temperature Tolerance)",
                 "Feathers over Hide (DR 1, +1 Temperature Tolerance)",
                 "Spines",
                 "Spines",
                 "Spines")

skin_exoskeleton = ("Light Exoskeleton (DR 0)",
                    "Light Exoskeleton (DR 0)",
                    "Tough Exoskeleton (DR 1)",
                    "Tough Exoskeleton (DR 1)",
                    "Heavy Exoskeleton (DR 2)",
                    "Armor Shell (DR 5)",
                    "Armor Shell (DR 5)",
                    "Armor Shell (DR 5)")

sexes = ("Asexual Reproduction or Parthenogenesis",
         "Asexual Reproduction or Parthenogenesis",
         "Asexual Reproduction or Parthenogenesis",
         "Hermaphrodite",
         "Hermaphrodite",
         "Two Sexes",
         "Two Sexes",
         "Two Sexes",
         "Switching between male and female",
         "Three or more",
         "Roll Twice")

numbers = ("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven",
           "Eight", "Nine", "Ten", "Eleven", "Twelve")

gestation = ("Spawning/Pollinating",
             "Egg-Laying",
             "Live-Bearing",
             "Live-Bearing with Pouch")

ui_chemical_basis = ["Hydrogen-Based",
                     "Ammonia-Based",
                     "Hydrocarbon-Based",
                     "Water-Based",
                     "Chlorine-Based",
                     "Silicon/Sulfuric Acid",
                     "Silicon/Liquid Sulfur",
                     "Silicon/Liquid Rock",
                     "Plasma",
                     "Exotica"]

ui_hab_type = ["Space-Dwelling",
               "Gas Giant",
               "Planetary Interior",
               "Water",
               "Land"]

ui_habitat = ["Plains",
              "Desert",
              "Island/Beach",
              "Woodlands",
              "Swampland",
              "Mountain",
              "Arctic",
              "Jungle",
              "Banks",
              "Open Ocean",
              "Fresh-Water Lakes",
              "River/Stream",
              "Tropical Lagoon",
              "Deep-Ocean Vents",
              "Salt-Water Sea",
              "Reef"]

ui_trophic_level = ["Combined",
                    "Autotroph",
                    "Decomposer",
                    "Scavenger",
                    "Omnivore",
                    "Gathering Herbivore",
                    "Grazing/Browsing Herbivore",
                    "Pouncing Carnivore",
                    "Chasing Carnivore",
                    "Trapping Carnivore",
                    "Hijacking Carnivore",
                    "Filter-Feeder",
                    "Parasite/Symbiont",
                    "Photosynthetic Autotroph",
                    "Chemosynthetic Autotroph",
                    "Exotic Autotroph"]

ui_locomotion = ["Immobile",
                 "Floating",
                 "Swimming",
                 "Sailing",
                 "Digging",
                 "Slithering",
                 "Walking",
                 "Climbing",
                 "Winged Flight",
                 "Bouyant Flight",
                 "Special",
                 "Solar Sail",
                 "Rocket"]

ui_size_class = ["Small",
                 "Human-Scale",
                 "Large",
                 "Huge"]

ui_symmetry = ["Bilateral",
               "Trilateral",
               "Radial",
               "Spherical",
               "Asymmetric"]

ui_tail_features = ["None",
                    "Striker",
                    "Long",
                    "Constricting",
                    "Barbed Striker",
                    "Gripping",
                    "Branching",
                    "Combination"]

ui_skeleton = ["None",
               "Hydrostatic",
               "External",
               "Internal",
               "Combination"]

ui_skin_type = ["Skin",
                "Scales",
                "Fur",
                "Feathers",
                "Exoskeleton"]

ui_skin = ["Soft Skin",
           "Normal Skin",
           "Hide",
           "Thick Hide",
           "Blubber",
           "Scales",
           "Heavy Scales",
           "Fur",
           "Thick Fur",
           "Thick Fur over Hide",
           "Spines",
           "Feathers",
           "Thick Feathers",
           "Feathers over Hide",
           "Light Exoskeleton",
           "Tough Exoskeleton",
           "Heavy Exoskeleton",
           "Armor Shell"]

ui_skin_map = {"Soft Skin": "Soft Skin",
               "Normal Skin": "Normal Skin",
               "Hide": "Hide (DR 1)",
               "Thick Hide": "Thick Hide (DR 4)",
               "Blubber": "Blubber",
               "Scales": "Scales (DR 1)",
               "Heavy Scales": "Heavy Scales (DR 3)",
               "Fur": "Fur",
               "Thick Fur": "Thick Fur (+1 Temperature Tolerance)",
               "Thick Fur over Hide": "Thick Fur over Hide (DR 1, +1 Temperature Tolerance)",
               "Spines": "Spines",
               "Feathers": "Feathers (+1 Temperature Tolerance)",
               "Thick Feathers": "Thick Feathers (+2 Temperature Tolerance)",
               "Feathers over Hide": "Feathers over Hide (DR 1, +1 Temperature Tolerance)",
               "Light Exoskeleton": "Light Exoskeleton (DR 0)",
               "Tough Exoskeleton": "Tough Exoskeleton (DR 1)",
               "Heavy Exoskeleton": "Heavy Exoskeleton (DR 2)",
               "Armor Shell": "Armor Shell (DR 5)"}

ui_breathing = ["Lungs",
                "Gills",
                "Lungs Storage",
                "Gills Other"]

ui_lungs_map = {
        "Lungs": "Lungs",
        "Gills": "Doesn't Breathe (Gills)",
        "Lungs Storage": "Lungs (air-breathing), Doesn't Breathe (Oxygen Storage)",
        "Gills Other": "Doesn't Breathe (Gills), Lungs (or convertable organ)"
        }

ui_temp = ["Cold-blooded-",
           "Cold-blooded",
           "Partial",
           "Warm-blooded",
           "Warm-blooded+"]

ui_temp_map = {
        "Cold-blooded-": "Cold-blooded (with disadvantage)",
        "Cold-blooded": "Cold-blooded (no disadvantage)",
        "Partial": "Partial regulation (temperature varies within limits)",
        "Warm-blooded": "Warm-blooded",
        "Warm-blooded+": "Warm-blooded (with Metabolism Control 2)"
        }

ui_growth = ["Metamorphosis",
             "Molting",
             "Continuous Growth",
             "Unusual"]

ui_sexes = ["Asexual Reproduction or Parthenogenesis",
            "Hermaphrodite",
            "Two Sexes",
            "Switching between male and female",
            "Three or more",
            "Roll Twice"]

ui_gestation = ["Spawning/Pollinating",
                "Egg-Laying",
                "Live-Bearing",
                "Live-Bearing with Pouch"]

ui_gestation_special = ["Brood Parasite",
                        "Parasitic Young",
                        "Cannibalistic Young Fatal",
                        "Cannibalistic Young"]

ui_gest_special_map = {
        "Brood Parasite": "Brood Parasite (raised by another species)",
        "Parasitic Young": "Parasitic Young (implanted in a host)",
        "Cannibalistic Young Fatal": "Cannibalistic Young (fatal to parent)",
        "Cannibalistic Young": "Cannibalistic Young (consume each other)"
        }

ui_reproductive_strategy = ["Strong K-Strategy",
                            "Moderate K-Strategy",
                            "Median Strategy",
                            "Moderate r-Strategy",
                            "Strong r-Strategy"]

ui_intelligence = ["Mindless",
                   "Preprogrammed",
                   "Low",
                   "High",
                   "Presapient",
                   "Sapient"]

ui_intel_map = {
        "Mindless": "Mindless",
        "Preprogrammed": "Preprogrammed (Cannot Learn)",
        "Low": "Low Intelligence (Bestial)",
        "High": "High Intelligence (Bestial)",
        "Presapient": "Presapient",
        "Sapient": "Sapient",
        }

ui_mating = ["No Bond",
             "Temp Pair",
             "Pair",
             "Harem",
             "Hive"]

ui_mating_map = {
        "No Bond": "Mating only, no pair bond",
        "Temp Pair": "Temporary pair bond",
        "Pair": "Permanent pair bond",
        "Harem": "Harem",
        "Hive": "Hive"
        }

ui_social = ["Solitary",
             "Pair",
             "Troop",
             "Pack",
             "Herd",
             "Hive"]

ui_social_map = {
        "Solitary": "Solitary",
        "Pair": "Pair-bonded",
        "Troop": "Troop of 4 - 10 members",
        "Pack": "Pack of 6 - 20 members",
        "Herd": "Herd of 10+ members",
        "Hive": "Hive"
        }

csv_fields = [
        "chemical_basis",
        "habitat_type",
        "habitat",
        "trophic_level",
        "locomotion",
        "size_class",
        "size_volume",
        "size_mass",
        "size_weight",
        "stat_st",
        "stat_move_walk",
        "symmetry",
        "sides",
        "segments",
        "limbs",
        "tail",
        "manip",
        "manip_badgrip",
        "manip_normaldx",
        "manip_highdx",
        "manip_trunk",
        "skeleton",
        "skin",
        "breathing",
        "temperature_regulation",
        "growth_pattern",
        "sexes",
        "gestation",
        "gestation_special",
        "reproductive_strat",
        "sense_primary",
        "sense_vision",
        "sense_hearing",
        "sense_touch",
        "sense_tastesmell",
        "sense_specials",
        "comms_a",
        "comms_b",
        "intelligence",
        "stat_iq",
        "mating",
        "social_organization",
        "p_chauvinism",
        "p_chauvinism_trait",
        "p_concentration",
        "p_concentration_trait",
        "p_curiosity",
        "p_curiosity_trait",
        "p_egoism",
        "p_egoism_trait",
        "p_empathy",
        "p_empathy_trait",
        "p_gregariousness",
        "p_gregariousness_trait",
        "p_imagination",
        "p_imagination_trait",
        "p_suspicion",
        "p_suspicion_trait",
        "p_playfulness",
        "p_playfulness_trait"
        ]

csv_unused = [
        "planet",
        "p_more_variation",
        "possible_sapient",
        "sapient",
        "wingspan",
        "_is_carnivore",
        "_is_flying",
        "_is_autotroph",
        "_is_herbivore"
        ]
